import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/lib/sessionWrapper";
import { Toaster } from "react-hot-toast"; // Import Toaster



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
   
        <SessionWrapper>
          {children}
        </SessionWrapper>
        <Toaster position="top-right" reverseOrder={false} /> {/* Add Toaster */}
      </body>
    </html>
  );
}
