import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/lib/sessionWrapper";
import { Toaster } from "react-hot-toast";

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Add Material Icons */}
        <link 
          href="https://fonts.googleapis.com/icon?family=Material+Icons" 
          rel="stylesheet"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
        <SessionWrapper>
          {children}
        </SessionWrapper>
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}